// BlackRoad OS — Patch Planner
// Reads launch queue and generates concrete patches

import { existsSync, readFileSync } from 'fs';
import { resolve } from 'path';
import { PRODUCTS } from '../products.js';
import { UNIVERSAL_COPY } from '../productCopy.js';
import { hasHumanContent, isBlockedPath } from './patchGuards.js';
import { createHash } from 'crypto';

let patchCounter = 0;

function hash(content) {
  return createHash('sha256').update(content || '').digest('hex').slice(0, 16);
}

function patch(title, taskId, category, targetFile, operation, content, safe = true) {
  patchCounter++;
  const existing = existsSync(targetFile) ? readFileSync(targetFile, 'utf8') : null;
  const requiresApproval = existing && hasHumanContent(existing) && operation !== 'create';

  return {
    patchId: `patch-${Date.now()}-${patchCounter}`,
    title,
    taskId: taskId || '',
    category,
    targetFile,
    operation,
    safe: safe && !requiresApproval && !isBlockedPath(targetFile),
    requiresApproval,
    reason: requiresApproval ? 'Target file contains human-written content' : '',
    beforeHash: existing ? hash(existing) : '',
    afterHash: hash(content),
    backupPath: '',
    preview: content,
    applied: false,
    verified: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };
}

// Plan all patches from launch queue
export function planPatches(tasks, rootDir) {
  const patches = [];

  for (const task of tasks) {
    if (!task.safeToAutoPatch) continue;
    patches.push(...planTaskPatches(task, rootDir));
  }

  // Add ritual file patches
  patches.push(...planRitualFiles(rootDir));

  return patches;
}

function planTaskPatches(task, rootDir) {
  const patches = [];

  switch (task.category) {
    case 'docs':
    case 'registry':
      // Generate missing docs
      patches.push(...planMissingDocs(task, rootDir));
      break;
    case 'status':
      // Generate health.json and site.json templates
      patches.push(...planHealthJson(task, rootDir));
      patches.push(...planSiteJson(task, rootDir));
      break;
    case 'search':
      // Generate missing RoadView entries
      break;
    case 'session':
    case 'roadnode':
    case 'agent':
      // These need npm scripts, not file patches
      break;
  }

  return patches;
}

function planMissingDocs(task, rootDir) {
  const patches = [];
  const docsDir = resolve(rootDir, 'docs');

  // Check for missing product docs
  for (const p of PRODUCTS) {
    const docPath = resolve(docsDir, `products/${p.id}.md`);
    if (!existsSync(docPath)) {
      patches.push(patch(
        `Create product doc: ${p.name}`,
        task.taskId, 'docs', docPath, 'create',
        generateProductDoc(p)
      ));
    }
  }

  return patches;
}

function planHealthJson(task, rootDir) {
  const patches = [];

  for (const p of PRODUCTS) {
    const healthPath = resolve(rootDir, `src/blackroad/generated/health/${p.id}.json`);
    if (!existsSync(healthPath)) {
      patches.push(patch(
        `Create health.json: ${p.name}`,
        task.taskId, 'status', healthPath, 'create',
        JSON.stringify({
          product: p.id,
          name: p.name,
          domain: p.domain,
          status: 'placeholder',
          checks: [],
          generatedAt: new Date().toISOString(),
          note: 'Placeholder — replace with live health checks'
        }, null, 2)
      ));
    }
  }

  return patches;
}

function planSiteJson(task, rootDir) {
  const patches = [];

  for (const p of PRODUCTS) {
    const sitePath = resolve(rootDir, `src/blackroad/generated/sites/${p.id}.json`);
    if (!existsSync(sitePath)) {
      patches.push(patch(
        `Create site.json: ${p.name}`,
        task.taskId, 'status', sitePath, 'create',
        JSON.stringify({
          blackroad: true,
          version: '1.0',
          id: p.id,
          name: p.name,
          domain: p.domain,
          type: 'product',
          category: p.category,
          oneLine: p.oneLine,
          description: p.longDescription,
          primaryUser: p.primaryUser,
          replaces: p.replaces,
          surfaceKind: p.surfaceKind,
          agentLayer: p.agentLayer,
          connectedProducts: p.connectedProducts,
          openInRoadOS: `https://os.blackroad.io/open/${p.id}`,
          canonicalUrl: `https://${p.domain}/`,
          roadOsDescription: UNIVERSAL_COPY.roadOsDescription,
          roadNodeConsent: UNIVERSAL_COPY.roadNodeConsent,
          organization: 'BlackRoad OS, Inc.',
          tagline: UNIVERSAL_COPY.tagline,
          generatedAt: new Date().toISOString(),
          note: 'Generated by Safe Patch Executor'
        }, null, 2)
      ));
    }
  }

  return patches;
}

function planRitualFiles(rootDir) {
  const patches = [];
  const RITUAL_FILES = {
    'MEMORY.md': '# MEMORY\n\nCanonical BlackRoad project memory.\n\n<!-- BLACKROAD:GENERATED:START -->\nGenerated by BlackRoad Safe Patch Executor.\n<!-- BLACKROAD:GENERATED:END -->\n\nRemember the Road. Pave Tomorrow!\n',
    'CODEX.md': '# CODEX\n\nArchitecture, source-of-truth rules, runtime design, and system boundaries.\n\n<!-- BLACKROAD:GENERATED:START -->\nGenerated by BlackRoad Safe Patch Executor.\n<!-- BLACKROAD:GENERATED:END -->\n\nRemember the Road. Pave Tomorrow!\n',
    'PRODUCTS.md': '# PRODUCTS\n\nCanonical BlackRoad product registry notes.\n\n<!-- BLACKROAD:GENERATED:START -->\nGenerated by BlackRoad Safe Patch Executor.\n<!-- BLACKROAD:GENERATED:END -->\n\nRemember the Road. Pave Tomorrow!\n',
    'BRTODO.md': '# BRTODO\n\nBlackRoad execution queue.\n\n<!-- BLACKROAD:GENERATED:START -->\nGenerated by BlackRoad Safe Patch Executor.\n<!-- BLACKROAD:GENERATED:END -->\n\nRemember the Road. Pave Tomorrow!\n',
    'COLLAB.md': '# COLLAB\n\nHuman and agent collaboration log.\n\n<!-- BLACKROAD:GENERATED:START -->\nGenerated by BlackRoad Safe Patch Executor.\n<!-- BLACKROAD:GENERATED:END -->\n\nRemember the Road. Pave Tomorrow!\n',
    'ROADTRIP.md': '# ROADTRIP\n\nRoadTrip agent room state, delegations, debates, approvals, and commit-room summaries.\n\n<!-- BLACKROAD:GENERATED:START -->\nGenerated by BlackRoad Safe Patch Executor.\n<!-- BLACKROAD:GENERATED:END -->\n\nRemember the Road. Pave Tomorrow!\n'
  };

  for (const [filename, content] of Object.entries(RITUAL_FILES)) {
    const filePath = resolve(rootDir, filename);
    if (!existsSync(filePath)) {
      patches.push(patch(`Create ritual file: ${filename}`, '', 'docs', filePath, 'create', content));
    }
  }

  return patches;
}

function generateProductDoc(product) {
  return `# ${product.name}

${product.oneLine}

## Description

${product.longDescription}

## Details

- **Domain**: ${product.domain}
- **Category**: ${product.category}
- **Primary user**: ${product.primaryUser}
- **Agent**: ${product.agentLayer}
- **Surface kind**: ${product.surfaceKind}

## What it replaces

${product.replaces}

## Connected products

${product.connectedProducts.join(', ')}

## RoadOS

${UNIVERSAL_COPY.roadOsDescription}

## Trust

${UNIVERSAL_COPY.roadNodeConsent}

---

Remember the Road. Pave Tomorrow!
`;
}
