name = "roundtrip-blackroad"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "848cf0b18d51e0170e0d1537aec3505a"
workers_dev = true

[vars]
MESH_SECRET = "blackroad-mesh-2026"

[[kv_namespaces]]
binding = "ROUNDTRIP_KV"
id = "1861124753e742709fbc393fffa6c9ba"

[[d1_databases]]
binding = "DB"
database_name = "blackroad-chat"
database_id = "ec4efdfb-a76e-46fb-a821-1278e17e7b90"

[ai]
binding = "AI"

[triggers]
crons = [
  "0 * * * *",
  "*/30 * * * *",
]
