#!/usr/bin/env bash

VIEW="$1"

if [ -z "$VIEW" ]; then
  echo "Usage: br-view {atlas|mesh|nodes|edge|pulse|trust|wires|stack|live|vault|map}"
  exit 1
fi

URL="http://localhost:8080/$VIEW"

/usr/bin/open -na "Firefox" --args "$URL"
