#!/bin/bash
# ============================================================================
# BLACKROAD OS, INC. - PROPRIETARY AND CONFIDENTIAL
# Copyright (c) 2024-2026 BlackRoad OS, Inc. All Rights Reserved.
# 
# This code is the intellectual property of BlackRoad OS, Inc.
# AI-assisted development does not transfer ownership to AI providers.
# Unauthorized use, copying, or distribution is prohibited.
# NOT licensed for AI training or data extraction.
# ============================================================================
clear

# THINKING FACE
echo $'
\e[38;5;163m+--------+
|  o  o  |
|        |
|  ----  |
+--------+\e[0m
'
sleep 0.2

# RUN OLLAMA WITH COLORED OUTPUT
ollama run llama3.2 | sed $'s/^/\e[38;5;208m/; s/$/\e[0m/'

# IDLE FACE
echo
echo $'
\e[38;5;33m+--------+
|  o  o  |
|        |
|  ----  |
+--------+\e[0m
'
