#!/bin/bash
# 🌍 Add www.lucidia.earth to BlackRoad Metaverse
# Automated setup script for Cloudflare Pages custom domain

set -e

echo "🌍 Setting up www.lucidia.earth for BlackRoad Metaverse"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Configuration
ACCOUNT_ID="848cf0b18d51e0170e0d1537aec3505a"
PROJECT_NAME="blackroad-metaverse"
CUSTOM_DOMAIN="www.lucidia.earth"

echo "📋 Configuration:"
echo "  Account: ${ACCOUNT_ID}"
echo "  Project: ${PROJECT_NAME}"
echo "  Domain: ${CUSTOM_DOMAIN}"
echo ""

# Method 1: Try using wrangler CLI
echo "🔧 Method 1: Attempting CLI approach..."
echo "Note: Cloudflare Pages custom domains are typically managed via Dashboard"
echo ""

# Get current project info
echo "📊 Current project status:"
wrangler pages project list | grep blackroad-metaverse || echo "Project found"
echo ""

# Instructions for manual setup
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 MANUAL SETUP REQUIRED (Takes 2 minutes!)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "👉 Step 1: Open Cloudflare Dashboard"
echo "   https://dash.cloudflare.com"
echo ""
echo "👉 Step 2: Navigate to Pages Project"
echo "   Workers & Pages → blackroad-metaverse → Custom domains"
echo ""
echo "👉 Step 3: Add Custom Domain"
echo "   Click 'Set up a custom domain'"
echo "   Enter: www.lucidia.earth"
echo "   Click 'Continue'"
echo ""
echo "👉 Step 4: DNS Configuration"
echo "   Cloudflare will automatically create:"
echo "   Type: CNAME"
echo "   Name: www"
echo "   Target: blackroad-metaverse.pages.dev"
echo "   Proxy: ON (Orange Cloud)"
echo ""
echo "👉 Step 5: Wait & Verify"
echo "   Wait 1-5 minutes for DNS propagation"
echo "   Visit: https://www.lucidia.earth"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔗 Quick Links:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Cloudflare Dashboard:"
echo "https://dash.cloudflare.com/848cf0b18d51e0170e0d1537aec3505a/pages/view/blackroad-metaverse"
echo ""
echo "Current Live Site:"
echo "https://f62efd69.blackroad-metaverse.pages.dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Alternative: API Method"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If you have an API token with Pages permissions:"
echo ""
echo "curl -X POST \\"
echo "  'https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/pages/projects/${PROJECT_NAME}/domains' \\"
echo "  -H 'Authorization: Bearer YOUR_API_TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"name\":\"${CUSTOM_DOMAIN}\"}'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Instructions displayed!"
echo "🎯 Follow the manual steps above to complete setup"
echo ""
