// BlackRoad OS — Canonical Product Registry
// 1 OS Shell + 17 Products = 18 Endpoints
// Locked 2026-04-24

export const PRODUCTS = [
  {
    id: 'roados',
    name: 'RoadOS',
    route: '/',
    domain: 'os.blackroad.io',
    category: 'os',
    oneLine: 'The portable browser computer.',
    longDescription: 'Log in from any device — iPhone, MacBook, Raspberry Pi, NVIDIA box, Apple TV, kiosk, classroom computer, or borrowed machine — and recover your apps, agents, files, surfaces, routes, and workspace inside one controlled OS tab.',
    primaryUser: 'everyone',
    replaces: 'Physical computer dependency. Your workspace tied to one device.',
    connectedProducts: ['roadtrip', 'roadcode', 'roadwork', 'roadview', 'roadside', 'highway'],
    agentLayer: 'lucidia',
    surfaceKind: 'shell',
    status: 'active',
    tags: ['os', 'shell', 'desktop', 'portable', 'core']
  },
  {
    id: 'roadcode',
    name: 'RoadCode',
    route: '/roadcode',
    domain: 'roadcode.blackroad.io',
    category: 'work',
    oneLine: 'The native coding environment.',
    longDescription: 'Code, preview, deploy, terminal, Git, Cloudflare, Railway, Vercel, MCP, and AI coding agents collapse into one place.',
    primaryUser: 'developers',
    replaces: 'VS Code + GitHub + Vercel + Railway + terminal tabs scattered everywhere.',
    connectedProducts: ['roados', 'carpool', 'roadchain', 'carkeys'],
    agentLayer: 'cecilia',
    surfaceKind: 'app',
    status: 'active',
    tags: ['code', 'deploy', 'terminal', 'git', 'ai']
  },
  {
    id: 'roadtrip',
    name: 'RoadTrip',
    route: '/roadtrip',
    domain: 'roadtrip.blackroad.io',
    category: 'core',
    oneLine: 'The flagship multi-agent executive room.',
    longDescription: 'One person can coordinate with 27 agents in a group chat, and those agents can branch into specialized agent teams behind the scenes.',
    primaryUser: 'operators',
    replaces: 'Slack + ChatGPT + multiple AI tabs + copy-pasting between agents.',
    connectedProducts: ['roados', 'carpool', 'roadwork', 'carkeys'],
    agentLayer: 'all',
    surfaceKind: 'app',
    status: 'active',
    tags: ['agents', 'chat', 'coordination', 'executive', 'core']
  },
  {
    id: 'pitstop',
    name: 'Pitstop',
    route: '/pitstop',
    domain: 'pitstop.blackroad.io',
    category: 'education',
    oneLine: 'The homework and learning portal.',
    longDescription: 'Khan Academy, Kahoot, Quizlet, Canvas, Schoology, tutoring, quizzes, teacher loops, and interactive learning for students who need support.',
    primaryUser: 'students',
    replaces: 'Khan Academy + Kahoot + Quizlet + Canvas + Schoology fragmentation.',
    connectedProducts: ['roados', 'roadbook', 'blackboard', 'roadtrip'],
    agentLayer: 'roadie',
    surfaceKind: 'app',
    status: 'active',
    tags: ['education', 'tutoring', 'quizzes', 'homework', 'learning']
  },
  {
    id: 'roadwork',
    name: 'RoadWork',
    route: '/roadwork',
    domain: 'roadwork.blackroad.io',
    category: 'work',
    oneLine: 'The work operating layer.',
    longDescription: 'Company formation, Stripe Atlas, Delaware filings, EIN tracking, board obligations, team collaboration, task routing, Salesforce/SAP/Slack/Teams-style workflows.',
    primaryUser: 'founders',
    replaces: 'Salesforce + SAP + Slack + Teams + Notion + spreadsheet chaos.',
    connectedProducts: ['roados', 'roadchain', 'carkeys', 'roadtrip', 'carpool'],
    agentLayer: 'valeria',
    surfaceKind: 'app',
    status: 'active',
    tags: ['work', 'tasks', 'teams', 'operations', 'enterprise']
  },
  {
    id: 'backroad',
    name: 'BackRoad',
    route: '/backroad',
    domain: 'backroad.blackroad.io',
    category: 'social',
    oneLine: 'The social media layer.',
    longDescription: 'Creator-first, comment-first, nostalgia-aware social feed that combines the best parts of Reddit, Tumblr, MySpace, Facebook, TikTok, Instagram, and Twitter without algorithmic sludge.',
    primaryUser: 'creators',
    replaces: 'Reddit + Tumblr + MySpace + Facebook + TikTok + Instagram + Twitter.',
    connectedProducts: ['roados', 'roadbook', 'blackboard', 'roadband', 'roadcoin'],
    agentLayer: 'calliope',
    surfaceKind: 'app',
    status: 'active',
    tags: ['social', 'creator', 'feed', 'comments', 'nostalgia']
  },
  {
    id: 'carkeys',
    name: 'CarKeys',
    route: '/carkeys',
    domain: 'carkeys.blackroad.io',
    category: 'infrastructure',
    oneLine: 'The access and identity layer.',
    longDescription: 'Instead of API keys everywhere, users get CarKeys: controlled identity, access, authentication, permissions, and signed routes.',
    primaryUser: 'everyone',
    replaces: 'Scattered API keys, OAuth flows, password managers, identity fragmentation.',
    connectedProducts: ['roados', 'roadchain', 'roadwork', 'roadtrip'],
    agentLayer: 'silas',
    surfaceKind: 'service',
    status: 'active',
    tags: ['auth', 'identity', 'permissions', 'keys', 'access']
  },
  {
    id: 'roadbook',
    name: 'RoadBook',
    route: '/roadbook',
    domain: 'roadbook.blackroad.io',
    category: 'knowledge',
    oneLine: 'The publishing and verification layer.',
    longDescription: 'Decentralized books, research, papers, peer review, proof frameworks, public knowledge, citations, and verified publishing.',
    primaryUser: 'researchers',
    replaces: 'arXiv + Medium + Substack + Google Scholar + broken peer review.',
    connectedProducts: ['roados', 'roadchain', 'roadview', 'pitstop'],
    agentLayer: 'sophia',
    surfaceKind: 'app',
    status: 'active',
    tags: ['publishing', 'research', 'papers', 'citations', 'knowledge']
  },
  {
    id: 'roadworld',
    name: 'RoadWorld',
    route: '/roadworld',
    domain: 'roadworld.blackroad.io',
    category: 'world',
    oneLine: 'The world layer.',
    longDescription: 'Habbo Hotel meets Metropolis 1998 meets Minecraft/Stardew/RollerCoaster Tycoon: pixel worlds, rooms, maps, offices, games, agents, and community spaces.',
    primaryUser: 'everyone',
    replaces: 'Habbo Hotel + Minecraft + virtual office apps + metaverse hype.',
    connectedProducts: ['roados', 'roadtrip', 'backroad', 'roadcoin'],
    agentLayer: 'thalia',
    surfaceKind: 'app',
    status: 'active',
    tags: ['world', 'pixel', 'rooms', 'games', 'community']
  },
  {
    id: 'roadview',
    name: 'RoadView',
    route: '/roadview',
    domain: 'roadview.blackroad.io',
    category: 'knowledge',
    oneLine: 'The search and verification layer.',
    longDescription: 'A better search engine with GitHub, web, comments, citations, verification, source trails, and anti-scam context.',
    primaryUser: 'everyone',
    replaces: 'Google Search + Stack Overflow + GitHub search + trust-nothing web.',
    connectedProducts: ['roados', 'roadbook', 'roadchain', 'backroad'],
    agentLayer: 'alexandria',
    surfaceKind: 'app',
    status: 'active',
    tags: ['search', 'verification', 'discovery', 'citations', 'truth']
  },
  {
    id: 'roadchain',
    name: 'RoadChain',
    route: '/roadchain',
    domain: 'roadchain.blackroad.io',
    category: 'infrastructure',
    oneLine: 'The ledger and memory layer.',
    longDescription: 'SHA-256-pinned provenance, rollback, audit trails, compliance records, version history, and memory checkpoints.',
    primaryUser: 'operators',
    replaces: 'Git log + compliance spreadsheets + broken audit trails.',
    connectedProducts: ['roados', 'carkeys', 'roadwork', 'roadcoin'],
    agentLayer: 'portia',
    surfaceKind: 'service',
    status: 'active',
    tags: ['ledger', 'provenance', 'audit', 'memory', 'compliance']
  },
  {
    id: 'roadside',
    name: 'RoadSide',
    route: '/roadside',
    domain: 'roadside.blackroad.io',
    category: 'core',
    oneLine: 'The simple gateway.',
    longDescription: 'The "where do you want to start?" layer. It helps people enter the system without being overwhelmed.',
    primaryUser: 'newcomers',
    replaces: 'Confusing onboarding flows and feature-dump landing pages.',
    connectedProducts: ['roados', 'pitstop', 'roadtrip', 'highway'],
    agentLayer: 'roadie',
    surfaceKind: 'app',
    status: 'active',
    tags: ['onboarding', 'gateway', 'start', 'welcome', 'simple']
  },
  {
    id: 'roadcoin',
    name: 'RoadCoin',
    route: '/roadcoin',
    domain: 'roadcoin.blackroad.io',
    category: 'infrastructure',
    oneLine: 'The utility credit layer.',
    longDescription: 'Not framed as money. RoadCoin rewards contribution: hosting nodes, creating media, helping the fleet, doing useful work, or supporting the network.',
    primaryUser: 'contributors',
    replaces: 'Crypto speculation + platform-locked creator funds + no reward for contribution.',
    connectedProducts: ['roados', 'roadchain', 'highway', 'backroad'],
    agentLayer: 'sapphira',
    surfaceKind: 'service',
    status: 'active',
    tags: ['credits', 'rewards', 'contribution', 'utility', 'economy']
  },
  {
    id: 'carpool',
    name: 'CarPool',
    route: '/carpool',
    domain: 'carpool.blackroad.io',
    category: 'work',
    oneLine: 'The collaborative project layer.',
    longDescription: 'Multiple humans plus multiple AI agents working together in one shared project space.',
    primaryUser: 'teams',
    replaces: 'Google Docs + Figma + Notion + separate AI tools per person.',
    connectedProducts: ['roados', 'roadtrip', 'roadcode', 'roadwork'],
    agentLayer: 'valeria',
    surfaceKind: 'app',
    status: 'active',
    tags: ['collaboration', 'projects', 'teams', 'shared', 'workspace']
  },
  {
    id: 'blackboard',
    name: 'BlackBoard',
    route: '/blackboard',
    domain: 'blackboard.blackroad.io',
    category: 'creative',
    oneLine: 'The creation layer.',
    longDescription: 'Drag-and-drop creative automation for people who want to make media, design, graphics, websites, lessons, posts, and visual systems without mastering Adobe/Dreamweaver-style tools.',
    primaryUser: 'creators',
    replaces: 'Adobe Creative Suite + Canva + Dreamweaver + scattered design tools.',
    connectedProducts: ['roados', 'backroad', 'roadbook', 'roadband'],
    agentLayer: 'lyra',
    surfaceKind: 'app',
    status: 'active',
    tags: ['creative', 'design', 'media', 'drag-drop', 'automation']
  },
  {
    id: 'oneway',
    name: 'OneWay',
    route: '/oneway',
    domain: 'oneway.blackroad.io',
    category: 'infrastructure',
    oneLine: 'The import and memory-ingestion layer.',
    longDescription: 'External APIs, exports, memories, and data streams come into BlackRoad through a one-way controlled route so the system can remember without exposing itself backward.',
    primaryUser: 'operators',
    replaces: 'Zapier + IFTTT + manual CSV imports + broken API integrations.',
    connectedProducts: ['roados', 'roadchain', 'carkeys', 'roadview'],
    agentLayer: 'elias',
    surfaceKind: 'service',
    status: 'active',
    tags: ['import', 'ingestion', 'migration', 'api', 'one-way']
  },
  {
    id: 'roadband',
    name: 'RoadBand',
    route: '/roadband',
    domain: 'roadband.blackroad.io',
    category: 'creative',
    oneLine: 'The music and audio creation layer.',
    longDescription: 'GarageBand plus AI producer workflows: choose beats, tracks, vocals, moods, lyrics, styles, and assemble music interactively.',
    primaryUser: 'musicians',
    replaces: 'GarageBand + scattered AI music tools + no producer workflow.',
    connectedProducts: ['roados', 'blackboard', 'backroad', 'roadcoin'],
    agentLayer: 'aria',
    surfaceKind: 'app',
    status: 'active',
    tags: ['music', 'audio', 'beats', 'vocals', 'producer']
  },
  {
    id: 'highway',
    name: 'HighWay',
    route: '/highway',
    domain: 'highway.blackroad.io',
    category: 'core',
    oneLine: 'The subscription and backbone layer.',
    longDescription: 'The umbrella platform: users can subscribe to the whole highway or individual roads/products.',
    primaryUser: 'subscribers',
    replaces: 'Multiple subscriptions + no unified access + feature fragmentation.',
    connectedProducts: ['roados', 'roadcoin', 'carkeys', 'roadside'],
    agentLayer: 'lucidia',
    surfaceKind: 'service',
    status: 'active',
    tags: ['subscription', 'backbone', 'pricing', 'bundle', 'access']
  }
];

// Category definitions
export const CATEGORIES = {
  os: { label: 'Operating System', color: '#ffffff' },
  core: { label: 'Core System', color: '#cccccc' },
  work: { label: 'Work & Creation', color: '#aaaaaa' },
  knowledge: { label: 'Knowledge & Discovery', color: '#999999' },
  social: { label: 'Social & Culture', color: '#888888' },
  creative: { label: 'Creative Tools', color: '#777777' },
  education: { label: 'Education', color: '#666666' },
  infrastructure: { label: 'Infrastructure & Economy', color: '#555555' },
  world: { label: 'World Layer', color: '#444444' }
};

// Lookup helpers
export const getProduct = (id) => PRODUCTS.find(p => p.id === id);
export const getByCategory = (cat) => PRODUCTS.filter(p => p.category === cat);
export const getByTag = (tag) => PRODUCTS.filter(p => p.tags.includes(tag));
export const getConnected = (id) => {
  const product = getProduct(id);
  return product ? product.connectedProducts.map(getProduct).filter(Boolean) : [];
};
