// BlackRoad OS — Site Registry
// Every website in the BlackRoad web operating territory

export const SITE_TYPES = {
  root: 'Root Brand Site',
  product: 'Product Site',
  runtime: 'OS Runtime',
  infrastructure: 'Infrastructure',
  agent: 'Agent Site',
  archive: 'Archive / Media',
  legal: 'Legal / Compliance',
  support: 'Support',
  developer: 'Developer',
  brand: 'Brand',
  billing: 'Billing',
  search: 'Search',
  live: 'Live / Broadcast'
};

export const SITES = [
  // ── ROOT BRAND SITES ──
  {
    id: 'blackroad-io',
    domain: 'blackroad.io',
    title: 'BlackRoad',
    type: 'root',
    purpose: 'What is BlackRoad? Main public portal, product launcher, search dock, public demo, OS entry.',
    primaryCTA: 'Open RoadOS',
    audience: 'everyone',
    connectedProduct: null,
    connectedAgents: ['lucidia', 'roadie'],
    status: 'active',
    priority: 1,
    routes: ['/', '/products', '/agents', '/about', '/demo', '/docs', '/open'],
    notes: 'The front door. Explains the whole system.'
  },
  {
    id: 'os-blackroad-io',
    domain: 'os.blackroad.io',
    title: 'RoadOS',
    type: 'runtime',
    purpose: 'The portable browser computer. Log in from any device and recover apps, agents, files, media, routes, and workspace.',
    primaryCTA: 'Enter OS',
    audience: 'users',
    connectedProduct: 'roados',
    connectedAgents: ['lucidia'],
    status: 'active',
    priority: 1,
    routes: ['/', '/desktop', '/dock', '/surfaces', '/settings', '/open/*'],
    notes: 'The actual computer. Everything opens inside this.'
  },
  {
    id: 'blackroad-company',
    domain: 'blackroad.company',
    title: 'BlackRoad Company',
    type: 'root',
    purpose: 'Corporate identity, founder page, formation, mission, business model.',
    primaryCTA: 'Learn about BlackRoad OS, Inc.',
    audience: 'investors',
    connectedProduct: null,
    connectedAgents: ['portia'],
    status: 'planned',
    priority: 2,
    routes: ['/', '/about', '/founder', '/mission', '/contact'],
    notes: 'Who owns it, what it does, why it exists.'
  },
  {
    id: 'blackroad-systems',
    domain: 'blackroad.systems',
    title: 'BlackRoad Systems',
    type: 'infrastructure',
    purpose: 'Technical stack. Edge AI, local-first compute, fleet, RoadNode, architecture.',
    primaryCTA: 'Explore the stack',
    audience: 'engineers',
    connectedProduct: null,
    connectedAgents: ['cecilia', 'octavia'],
    status: 'active',
    priority: 2,
    routes: ['/', '/fleet', '/dns', '/vpn', '/monitor'],
    notes: 'Explain the technical stack.'
  },
  {
    id: 'blackroad-network',
    domain: 'blackroad.network',
    title: 'BlackRoad Network',
    type: 'infrastructure',
    purpose: 'Distributed device network. RoadNode opt-in, fleet health, mesh, tunnels, uptime, contribution.',
    primaryCTA: 'Learn about RoadNode',
    audience: 'node-operators',
    connectedProduct: null,
    connectedAgents: ['alice', 'olympia'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/nodes', '/mesh', '/opt-in', '/status'],
    notes: 'RoadNode opt-in, mesh, uptime.'
  },
  {
    id: 'blackroad-me',
    domain: 'blackroad.me',
    title: 'BlackRoad Me',
    type: 'root',
    purpose: 'People, agents, profiles, portable identity.',
    primaryCTA: 'Find an agent',
    audience: 'everyone',
    connectedProduct: null,
    connectedAgents: ['all'],
    status: 'planned',
    priority: 2,
    routes: ['/', '/:agentName'],
    notes: 'Agent subdomains and human-facing profile pages.'
  },
  {
    id: 'blackroadai-com',
    domain: 'blackroadai.com',
    title: 'BlackRoad AI',
    type: 'root',
    purpose: 'AI brand. Agents, local models, RoadTrip, Lucidia, Roadie.',
    primaryCTA: 'Meet the Roadies',
    audience: 'ai-curious',
    connectedProduct: 'roadtrip',
    connectedAgents: ['lucidia', 'roadie'],
    status: 'active',
    priority: 2,
    routes: ['/', '/chat', '/models', '/docs', '/api'],
    notes: 'AI marketing and AI assistant discoverability.'
  },
  {
    id: 'blackboxprogramming-io',
    domain: 'blackboxprogramming.io',
    title: 'BlackBox Programming',
    type: 'developer',
    purpose: 'Coding, experiments, dev logs, technical credibility.',
    primaryCTA: 'See the code',
    audience: 'developers',
    connectedProduct: 'roadcode',
    connectedAgents: ['cecilia'],
    status: 'active',
    priority: 2,
    routes: ['/', '/docs', '/playground', '/sdk', '/cli'],
    notes: 'RoadCode, programming, founder coding story.'
  },
  {
    id: 'roadchain-io',
    domain: 'roadchain.io',
    title: 'RoadChain',
    type: 'root',
    purpose: 'Proof, memory, rollback, audit trails.',
    primaryCTA: 'Explore the ledger',
    audience: 'auditors',
    connectedProduct: 'roadchain',
    connectedAgents: ['portia'],
    status: 'active',
    priority: 2,
    routes: ['/', '/explorer', '/validator', '/docs', '/testnet'],
    notes: 'SHA-256 pins, compliance, chain explorer.'
  },
  {
    id: 'roadcoin-io',
    domain: 'roadcoin.io',
    title: 'RoadCoin',
    type: 'root',
    purpose: 'Utility credits. Contribution credits, usage credits, creator rewards, node rewards.',
    primaryCTA: 'Learn about credits',
    audience: 'contributors',
    connectedProduct: 'roadcoin',
    connectedAgents: ['sapphira'],
    status: 'active',
    priority: 2,
    routes: ['/', '/wallet', '/earn', '/spend', '/docs'],
    notes: 'Frame as utility credits, NOT investment money.'
  },
  {
    id: 'lucidia-studio',
    domain: 'lucidia.studio',
    title: 'Lucidia Studio',
    type: 'root',
    purpose: 'Creative AI studio. Lucidia, RoadBand, BlackBoard, media tools.',
    primaryCTA: 'Create something',
    audience: 'creators',
    connectedProduct: 'blackboard',
    connectedAgents: ['lucidia', 'lyra'],
    status: 'active',
    priority: 2,
    routes: ['/', '/canvas', '/video', '/audio', '/write'],
    notes: 'Creative AI studio.'
  },
  {
    id: 'lucidia-earth',
    domain: 'lucidia.earth',
    title: 'Lucidia Earth',
    type: 'root',
    purpose: 'Sustainability, education, environment, public-good layer.',
    primaryCTA: 'Explore stewardship',
    audience: 'educators',
    connectedProduct: null,
    connectedAgents: ['gaia'],
    status: 'active',
    priority: 3,
    routes: ['/', '/chat', '/memory', '/journal', '/learn'],
    notes: 'Stewardship, education, environment.'
  },
  {
    id: 'lucidiaqi-com',
    domain: 'lucidiaqi.com',
    title: 'Lucidia QI',
    type: 'root',
    purpose: 'Math, reasoning, symbolic systems, AI research.',
    primaryCTA: 'Read the research',
    audience: 'researchers',
    connectedProduct: null,
    connectedAgents: ['sophia'],
    status: 'active',
    priority: 3,
    routes: ['/', '/phi', '/trinary', '/belief', '/creative'],
    notes: 'Research, intelligence, symbolic thought layer.'
  },

  // ── PRODUCT SITES ──
  // These are auto-generated from products.js — each gets the 10 standard pages
  // See productRoutes.js for route generation

  // ── UTILITY SITES ──
  {
    id: 'docs-blackroad-io',
    domain: 'docs.blackroad.io',
    title: 'Docs',
    type: 'infrastructure',
    purpose: 'Documentation for humans and agents.',
    primaryCTA: 'Read the docs',
    audience: 'everyone',
    connectedProduct: null,
    connectedAgents: ['atticus'],
    status: 'active',
    priority: 1,
    routes: ['/', '/products', '/agents', '/api', '/guides', '/search'],
    notes: 'Explanation layer.'
  },
  {
    id: 'api-blackroad-io',
    domain: 'api.blackroad.io',
    title: 'API',
    type: 'developer',
    purpose: 'API gateway, SDKs, examples, auth rules.',
    primaryCTA: 'Explore the API',
    audience: 'developers',
    connectedProduct: null,
    connectedAgents: ['sebastian'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/reference', '/sdks', '/auth', '/examples'],
    notes: 'API gateway.'
  },
  {
    id: 'status-blackroad-io',
    domain: 'status.blackroad.io',
    title: 'Status',
    type: 'infrastructure',
    purpose: 'Uptime, fleet, deployments, incidents.',
    primaryCTA: 'Check status',
    audience: 'everyone',
    connectedProduct: null,
    connectedAgents: ['octavia'],
    status: 'active',
    priority: 1,
    routes: ['/', '/fleet', '/incidents', '/history'],
    notes: 'Proof layer.'
  },
  {
    id: 'brand-blackroad-io',
    domain: 'brand.blackroad.io',
    title: 'Brand',
    type: 'brand',
    purpose: 'Brand kit, logos, design system, copy rules.',
    primaryCTA: 'Get the brand kit',
    audience: 'partners',
    connectedProduct: null,
    connectedAgents: ['thalia'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/logos', '/colors', '/type', '/copy'],
    notes: 'Brand kit.'
  },
  {
    id: 'security-blackroad-io',
    domain: 'security.blackroad.io',
    title: 'Security',
    type: 'legal',
    purpose: 'Security model, RoadNode consent, sandboxing, responsible disclosure.',
    primaryCTA: 'Read security model',
    audience: 'auditors',
    connectedProduct: null,
    connectedAgents: ['silas', 'seraphina'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/model', '/roadnode', '/disclosure', '/audit'],
    notes: 'Security model.'
  },
  {
    id: 'legal-blackroad-io',
    domain: 'legal.blackroad.io',
    title: 'Legal',
    type: 'legal',
    purpose: 'Terms, privacy, acceptable use, data rights, compliance notes.',
    primaryCTA: 'Read terms',
    audience: 'everyone',
    connectedProduct: null,
    connectedAgents: ['portia'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/terms', '/privacy', '/acceptable-use', '/data-rights'],
    notes: 'Legal docs.'
  },
  {
    id: 'support-blackroad-io',
    domain: 'support.blackroad.io',
    title: 'Support',
    type: 'support',
    purpose: 'Help desk, support routes, RoadSide entry.',
    primaryCTA: 'Get help',
    audience: 'everyone',
    connectedProduct: 'roadside',
    connectedAgents: ['roadie'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/help', '/feedback', '/community'],
    notes: 'Help desk.'
  },
  {
    id: 'billing-blackroad-io',
    domain: 'billing.blackroad.io',
    title: 'Billing',
    type: 'billing',
    purpose: 'Plans, usage, RoadCoin credits, HighWay subscription.',
    primaryCTA: 'View plans',
    audience: 'subscribers',
    connectedProduct: 'highway',
    connectedAgents: ['sapphira'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/plans', '/usage', '/credits'],
    notes: 'Plans and usage.'
  },
  {
    id: 'account-blackroad-io',
    domain: 'account.blackroad.io',
    title: 'Account',
    type: 'infrastructure',
    purpose: 'Profile, sessions, devices, CarKeys, permissions.',
    primaryCTA: 'Manage account',
    audience: 'users',
    connectedProduct: 'carkeys',
    connectedAgents: ['silas'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/profile', '/sessions', '/devices', '/permissions'],
    notes: 'Account management.'
  },
  {
    id: 'admin-blackroad-io',
    domain: 'admin.blackroad.io',
    title: 'Admin',
    type: 'infrastructure',
    purpose: 'Internal operator console.',
    primaryCTA: 'Open console',
    audience: 'operators',
    connectedProduct: null,
    connectedAgents: ['octavia'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/fleet', '/agents', '/logs', '/config'],
    notes: 'Internal only.'
  },
  {
    id: 'fleet-blackroad-io',
    domain: 'fleet.blackroad.io',
    title: 'Fleet',
    type: 'infrastructure',
    purpose: 'Node health, mesh status, opt-in RoadNode map.',
    primaryCTA: 'View fleet',
    audience: 'operators',
    connectedProduct: null,
    connectedAgents: ['olympia', 'alice'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/nodes', '/mesh', '/health', '/map'],
    notes: 'Fleet dashboard.'
  },
  {
    id: 'archive-blackroad-io',
    domain: 'archive.blackroad.io',
    title: 'Archive',
    type: 'archive',
    purpose: 'Public-domain media, saved streams, documents, research archive.',
    primaryCTA: 'Browse archive',
    audience: 'everyone',
    connectedProduct: null,
    connectedAgents: ['alexandria'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/media', '/streams', '/documents', '/research'],
    notes: 'Public archive.'
  },
  {
    id: 'live-blackroad-io',
    domain: 'live.blackroad.io',
    title: 'Live',
    type: 'live',
    purpose: 'Live broadcast, commentary, agent reactions, media rooms.',
    primaryCTA: 'Watch live',
    audience: 'everyone',
    connectedProduct: null,
    connectedAgents: ['cicero', 'calliope'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/broadcast', '/rooms', '/schedule'],
    notes: 'Live broadcast.'
  },
  {
    id: 'search-blackroad-io',
    domain: 'search.blackroad.io',
    title: 'Search',
    type: 'search',
    purpose: 'Standalone RoadView search surface.',
    primaryCTA: 'Search everything',
    audience: 'everyone',
    connectedProduct: 'roadview',
    connectedAgents: ['alexandria'],
    status: 'active',
    priority: 2,
    routes: ['/', '/results', '/sources', '/verify'],
    notes: 'Standalone search.'
  },
  {
    id: 'agents-blackroad-io',
    domain: 'agents.blackroad.io',
    title: 'Agents',
    type: 'infrastructure',
    purpose: 'Agent command center / public agent demo.',
    primaryCTA: 'Meet the Roadies',
    audience: 'everyone',
    connectedProduct: 'roadtrip',
    connectedAgents: ['all'],
    status: 'active',
    priority: 1,
    routes: ['/', '/roster', '/demo', '/chat', '/status'],
    notes: 'Agent demo layer.'
  },
  {
    id: 'atlas-blackroad-io',
    domain: 'atlas.blackroad.io',
    title: 'Atlas',
    type: 'infrastructure',
    purpose: 'Map of products, domains, agents, orgs, routes, nodes.',
    primaryCTA: 'Explore the map',
    audience: 'everyone',
    connectedProduct: null,
    connectedAgents: ['lucidia'],
    status: 'planned',
    priority: 3,
    routes: ['/', '/products', '/domains', '/agents', '/routes'],
    notes: 'Ecosystem map.'
  },

  // ── AGENT SITES ──
  ...buildAgentSites()
];

function buildAgentSites() {
  const agents = [
    { name: 'roadie', title: 'Roadie', role: 'Personal operator assistant' },
    { name: 'lucidia', title: 'Lucidia', role: 'System narrator / memory / architecture guide' },
    { name: 'cecilia', title: 'Cecilia', role: 'AI engineer' },
    { name: 'octavia', title: 'Octavia', role: 'DevOps lead' },
    { name: 'alice', title: 'Alice', role: 'Gateway / network manager' },
    { name: 'aria', title: 'Aria', role: 'Audio / network / media routing' },
    { name: 'gematria', title: 'Gematria', role: 'Edge compute / math / infrastructure' },
    { name: 'anastasia', title: 'Anastasia', role: 'Cloud architect' },
    { name: 'alexandria', title: 'Alexandria', role: 'Knowledge manager' },
    { name: 'theodosia', title: 'Theodosia', role: 'QA engineer' },
    { name: 'sophia', title: 'Sophia', role: 'Research scientist' },
    { name: 'sapphira', title: 'Sapphira', role: 'Analytics lead' },
    { name: 'seraphina', title: 'Seraphina', role: 'AI safety lead' },
    { name: 'gaia', title: 'Gaia', role: 'Sustainability / environment' },
    { name: 'portia', title: 'Portia', role: 'Legal and compliance' },
    { name: 'atticus', title: 'Atticus', role: 'Documentation' },
    { name: 'cicero', title: 'Cicero', role: 'Communications' },
    { name: 'valeria', title: 'Valeria', role: 'Product manager' },
    { name: 'ophelia', title: 'Ophelia', role: 'Community' },
    { name: 'lyra', title: 'Lyra', role: 'Music and media' },
    { name: 'calliope', title: 'Calliope', role: 'Content creator' },
    { name: 'thalia', title: 'Thalia', role: 'UX / design' },
    { name: 'celeste', title: 'Celeste', role: 'Frontend' },
    { name: 'elias', title: 'Elias', role: 'Data' },
    { name: 'silas', title: 'Silas', role: 'Security' },
    { name: 'sebastian', title: 'Sebastian', role: 'Backend' },
    { name: 'olympia', title: 'Olympia', role: 'Performance / robotics / fleet testing' }
  ];

  return agents.map(a => ({
    id: `${a.name}-blackroad-me`,
    domain: `${a.name}.blackroad.me`,
    title: a.title,
    type: 'agent',
    purpose: a.role,
    primaryCTA: `Talk to ${a.title}`,
    audience: 'everyone',
    connectedProduct: 'roadtrip',
    connectedAgents: [a.name],
    status: 'planned',
    priority: 3,
    routes: ['/', '/chat', '/memory', '/status'],
    notes: `Lightweight profile/operator surface for ${a.title}.`
  }));
}

// Lookup helpers
export const getSite = (id) => SITES.find(s => s.id === id);
export const getByType = (type) => SITES.filter(s => s.type === type);
export const getByPriority = (p) => SITES.filter(s => s.priority === p);
export const getActive = () => SITES.filter(s => s.status === 'active');
export const getPhase1 = () => SITES.filter(s => s.priority === 1);
export const getPhase2 = () => SITES.filter(s => s.priority === 2);
export const getPhase3 = () => SITES.filter(s => s.priority === 3);

// Counts
export const TOTAL_SITES = SITES.length;
export const SITE_COUNTS = {
  root: getByType('root').length,
  product: 17, // from products.js
  utility: getByType('infrastructure').length + getByType('developer').length + getByType('legal').length + getByType('support').length + getByType('billing').length + getByType('brand').length + getByType('search').length + getByType('live').length + getByType('archive').length,
  agent: getByType('agent').length
};
