#!/bin/bash

# Push workflows to all BlackRoad-OS repositories

WORKFLOW_SOURCE="/Users/alexa/blackroad-workflows/.github"
TEMP_DIR="/tmp/blackroad-workflow-deploy"
ORG="BlackRoad-OS"

# Get all repos from the org
echo "🔍 Fetching repository list from $ORG..."
REPOS=$(gh repo list "$ORG" --limit 100 --json name --jq '.[].name')

# Create temp directory
rm -rf "$TEMP_DIR"
mkdir -p "$TEMP_DIR"

SUCCESS_COUNT=0
FAIL_COUNT=0
SKIP_COUNT=0

for REPO in $REPOS; do
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "📦 Processing: $ORG/$REPO"

  REPO_DIR="$TEMP_DIR/$REPO"

  # Clone the repo
  if gh repo clone "$ORG/$REPO" "$REPO_DIR" -- --depth 1; then
    cd "$REPO_DIR" || continue

    # Create .github/workflows if it doesn't exist
    mkdir -p .github/workflows

    # Copy workflows
    cp -r "$WORKFLOW_SOURCE/workflows/"* .github/workflows/

    # Check if there are changes
    if git status --porcelain | grep -q .; then
      # Stage and commit
      git add .github/workflows/
      git commit -m "ci: add automated CI/CD workflows

- Auto Deploy: Deploys to Railway/Cloudflare on PR and push
- Auto Merge: Approves and merges PRs when CI passes
- CI: Runs lint, tests, and builds

🤖 Generated by BlackRoad OS Automation"

      # Push - try main first, then master
      if git push origin main 2>/dev/null; then
        echo "✅ $REPO - Workflows pushed to main"
        ((SUCCESS_COUNT++))
      elif git push origin master 2>/dev/null; then
        echo "✅ $REPO - Workflows pushed to master"
        ((SUCCESS_COUNT++))
      else
        echo "❌ $REPO - Failed to push"
        ((FAIL_COUNT++))
      fi
    else
      echo "⏭️  $REPO - No changes needed (workflows may already exist)"
      ((SKIP_COUNT++))
    fi

    cd "$TEMP_DIR" || exit
    rm -rf "$REPO_DIR"
  else
    echo "⚠️  $REPO - Could not clone"
    ((FAIL_COUNT++))
  fi
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Deployment Complete!"
echo "   ✅ Updated: $SUCCESS_COUNT"
echo "   ⏭️  Skipped: $SKIP_COUNT"
echo "   ❌ Failed:  $FAIL_COUNT"
echo ""

# Cleanup
rm -rf "$TEMP_DIR"
