import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "roados",
    name: "RoadOS",
    route: "/home/apps/RoadOS/",
    domain: "os.blackroad.io",
    category: "os",
    oneLine: "Portable browser computer.",
    longDescription:
      "RoadOS is a virtual computer inside the browser. A user can open os.blackroad.io from any device, log in, and recover their working environment — apps, agents, files, routes, media, and workspace — inside one secured OS shell tab.",
    primaryUser: "Any user who wants a portable working environment across devices.",
    replaces: ["Device-bound desktops", "Single-machine workspaces"],
    connectedProducts: [
      "roadcode",
      "roadtrip",
      "carkeys",
      "carpool",
      "oneway",
      "roadside",
      "roadchain",
      "roadview",
    ],
    agentLayer: "Hosts app surfaces and agent surfaces inside one system boundary.",
    surfaceKind: "portable-computer",
    status: "partial",
    tags: ["portable", "browser-os", "workspace", "continuity"],
  },
  {
    id: "roadcode",
    name: "RoadCode",
    route: "/home/apps/RoadCode/",
    domain: "roadcode.blackroad.io",
    category: "dev",
    oneLine: "Native coding and deployment environment.",
    longDescription:
      "RoadCode collapses code, preview, deploy, terminal, Git, Cloudflare/Railway/Vercel, APIs, MCP routes, and AI coding agents into one place.",
    primaryUser: "Builders and developers shipping software.",
    replaces: ["Scattered CLIs", "Disconnected editors", "Ad-hoc deploy tabs"],
    connectedProducts: ["roados", "oneway", "roadchain", "roadview"],
    agentLayer: "Coding and deploy agents coordinate changes, tests, and releases.",
    surfaceKind: "runtime-app",
    status: "partial",
    tags: ["code", "deploy", "git", "terminal", "mcp"],
  },
  {
    id: "roadtrip",
    name: "RoadTrip",
    route: "/home/apps/RoadTrip/",
    domain: "roadtrip.blackroad.io",
    category: "agents",
    oneLine: "27-agent executive command room.",
    longDescription:
      "RoadTrip is the flagship multi-agent executive group chat. One human coordinates with 27 agents, and agents can branch into specialized agent teams behind the scenes.",
    primaryUser: "Operators coordinating complex work with multi-agent support.",
    replaces: ["One-chat assistants", "Fragmented agent tabs"],
    connectedProducts: ["roados", "roadwork", "roadcode", "roadchain", "oneway"],
    agentLayer: "The multi-agent layer (27 agents) routes work, memory, and verification.",
    surfaceKind: "runtime-app",
    status: "partial",
    tags: ["agents", "coordination", "workflows"],
  },
  {
    id: "pitstop",
    name: "Pitstop",
    route: "/home/apps/Pitstop/",
    domain: "pitstop.blackroad.io",
    category: "learning",
    oneLine: "Homework, tutoring, quizzes, and classroom loops.",
    longDescription:
      "Pitstop is the homework and learning portal: tutoring, quizzes, teacher loops, and interactive learning for students who need support.",
    primaryUser: "Students, parents, teachers, and tutors.",
    replaces: ["Scattered learning portals", "One-off tutoring threads"],
    connectedProducts: ["roados", "roadview", "roadbook"],
    agentLayer: "Tutor and classroom agents assist with lessons and verification.",
    surfaceKind: "learning",
    status: "needs-review",
    tags: ["education", "tutoring", "quizzes"],
  },
  {
    id: "roadwork",
    name: "RoadWork",
    route: "/home/apps/RoadWork/",
    domain: "roadwork.blackroad.io",
    category: "work",
    oneLine: "Company formation and operations system.",
    longDescription:
      "RoadWork coordinates real work: company formation, filings, tasks, teams, board obligations, Stripe Atlas, and enterprise-style workflows.",
    primaryUser: "Founders, operators, teams.",
    replaces: ["Spreadsheet ops", "Disconnected task stacks", "One-off compliance docs"],
    connectedProducts: ["roados", "carkeys", "roadchain", "carpool", "roadtrip"],
    agentLayer: "Ops agents route filings, tasks, and compliance checklists.",
    surfaceKind: "work",
    status: "partial",
    tags: ["operations", "formation", "tasks", "workflows"],
  },
  {
    id: "backroad",
    name: "BackRoad",
    route: "/home/apps/BackRoad/",
    domain: "backroad.blackroad.io",
    category: "social",
    oneLine: "Creator-first social media layer.",
    longDescription:
      "BackRoad is a creator-first, comment-first social layer with nostalgia-aware feeds and no algorithmic sludge as the primary interface.",
    primaryUser: "Creators and communities.",
    replaces: ["Algorithmic feeds", "Engagement traps"],
    connectedProducts: ["roados", "blackboard", "roadband", "roadbook", "roadview"],
    agentLayer: "Community agents assist moderation, context, and publishing.",
    surfaceKind: "social",
    status: "needs-review",
    tags: ["social", "comments", "creator"],
  },
  {
    id: "carkeys",
    name: "CarKeys",
    route: "/home/apps/CarKeys/",
    domain: "carkeys.blackroad.io",
    category: "identity",
    oneLine: "Identity, auth, access, and permissions layer.",
    longDescription:
      "CarKeys replaces API keys scattered everywhere with controlled identity, authentication, permissions, and signed routes across the ecosystem.",
    primaryUser: "Any user with sessions, devices, and permissions to manage.",
    replaces: ["Loose API keys", "Undocumented access rules"],
    connectedProducts: ["roados", "roadwork", "oneway", "roadtrip"],
    agentLayer: "Auth and policy agents enforce permissioned routes and device/session control.",
    surfaceKind: "identity",
    status: "partial",
    tags: ["auth", "permissions", "identity"],
  },
  {
    id: "roadbook",
    name: "RoadBook",
    route: "/home/apps/RoadBook/",
    domain: "roadbook.blackroad.io",
    category: "publishing",
    oneLine: "Publishing and verification layer.",
    longDescription:
      "RoadBook is for publishing, papers, peer review, proof frameworks, citations, and verified knowledge — with source trails and continuity.",
    primaryUser: "Researchers, writers, students, reviewers.",
    replaces: ["Unverifiable posts", "Citation-free publishing"],
    connectedProducts: ["roadview", "roadchain", "roados"],
    agentLayer: "Research and citation agents build structured evidence trails.",
    surfaceKind: "publishing",
    status: "partial",
    tags: ["publishing", "citations", "verification"],
  },
  {
    id: "roadworld",
    name: "RoadWorld",
    route: "/home/apps/RoadWorld/",
    domain: "roadworld.blackroad.io",
    category: "world",
    oneLine: "Pixel world and community spaces.",
    longDescription:
      "RoadWorld is the world layer: pixel rooms, maps, offices, games, simulations, agent spaces, and community environments.",
    primaryUser: "Communities, teams, classrooms, creators.",
    replaces: ["Fragmented community spaces", "One-off virtual rooms"],
    connectedProducts: ["roados", "carpool", "backroad"],
    agentLayer: "World agents manage rooms, events, and context.",
    surfaceKind: "world",
    status: "needs-review",
    tags: ["world", "pixel", "rooms", "community"],
  },
  {
    id: "roadview",
    name: "RoadView",
    route: "/home/apps/RoadView/",
    domain: "roadview.blackroad.io",
    category: "search",
    oneLine: "Search and verification layer.",
    longDescription:
      "RoadView is search plus verification: source trails, citations, comments on results, GitHub-aware lookup, and anti-scam context.",
    primaryUser: "Anyone trying to find truth fast with source trails.",
    replaces: ["Opaque search", "Scammy results", "No provenance"],
    connectedProducts: ["roadbook", "roadchain", "roados"],
    agentLayer: "Verification agents annotate results with context and citations.",
    surfaceKind: "search",
    status: "partial",
    tags: ["search", "verification", "citations"],
  },
  {
    id: "roadchain",
    name: "RoadChain",
    route: "/home/apps/RoadChain/",
    domain: "roadchain.blackroad.io",
    category: "ledger",
    oneLine: "Ledger, provenance, and memory checkpoints.",
    longDescription:
      "RoadChain is the ledger and memory layer: SHA-256 pinned provenance, rollback, audit trails, compliance records, version history, and memory checkpoints.",
    primaryUser: "Operators who need proof, rollback, and auditability.",
    replaces: ["Handwavy logs", "Unverifiable history"],
    connectedProducts: ["roados", "roadwork", "oneway", "roadbook", "roadview"],
    agentLayer: "Ledger agents maintain audit trails, checkpoints, and integrity checks.",
    surfaceKind: "ledger",
    status: "partial",
    tags: ["provenance", "audit", "rollback", "sha256"],
  },
  {
    id: "roadside",
    name: "RoadSide",
    route: "/home/apps/RoadSide/",
    domain: "roadside.blackroad.io",
    category: "gateway",
    oneLine: "Simple onboarding gateway.",
    longDescription:
      "RoadSide is the simple gateway: “Where do you want to start?” It routes people into the ecosystem without overwhelm.",
    primaryUser: "New users entering the ecosystem.",
    replaces: ["Confusing link forests", "Dead-end marketing pages"],
    connectedProducts: ["roados", "roadview", "highway", "carkeys"],
    agentLayer: "Onboarding agents guide users into the correct surface.",
    surfaceKind: "gateway",
    status: "partial",
    tags: ["onboarding", "gateway", "routing"],
  },
  {
    id: "roadcoin",
    name: "RoadCoin",
    route: "/home/apps/RoadCoin/",
    domain: "roadcoin.blackroad.io",
    category: "credits",
    oneLine: "Utility credits and contribution rewards (not framed as money).",
    longDescription:
      "RoadCoin is a utility credit and contribution-reward layer. It rewards useful contribution (hosting nodes, creating media, helping the fleet, doing useful work) and supports internal usage credits — not investment money.",
    primaryUser: "Contributors and users earning/spending usage credits.",
    replaces: ["Opaque points", "Ad-hoc rewards"],
    connectedProducts: ["highway", "roadside", "roados", "roadwork"],
    agentLayer: "Accounting agents attribute contribution and usage credits with traceable rules.",
    surfaceKind: "creator",
    status: "needs-review",
    tags: ["credits", "rewards", "contribution"],
  },
  {
    id: "carpool",
    name: "CarPool",
    route: "/home/apps/CarPool/",
    domain: "carpool.blackroad.io",
    category: "work",
    oneLine: "Shared human + AI project workspace.",
    longDescription:
      "CarPool is the collaborative project layer: multiple humans and multiple AI agents working together in one shared project space.",
    primaryUser: "Teams shipping projects with AI co-workers.",
    replaces: ["Siloed project docs", "Untracked agent work"],
    connectedProducts: ["roados", "roadtrip", "roadcode", "roadchain"],
    agentLayer: "Project agents coordinate tasks, context, and handoffs.",
    surfaceKind: "work",
    status: "partial",
    tags: ["collaboration", "projects", "agents"],
  },
  {
    id: "blackboard",
    name: "BlackBoard",
    route: "/home/apps/BlackBoard/",
    domain: "blackboard.blackroad.io",
    category: "creator",
    oneLine: "Drag-and-drop creative automation.",
    longDescription:
      "BlackBoard is the creation layer: drag-and-drop creative automation for media, design, websites, lessons, posts, and visual systems without requiring Adobe-level mastery.",
    primaryUser: "Creators and operators producing assets quickly.",
    replaces: ["Heavy creative suites", "Manual repetitive production"],
    connectedProducts: ["backroad", "roadband", "roados"],
    agentLayer: "Creative agents generate drafts, layouts, and reusable components.",
    surfaceKind: "creator",
    status: "needs-review",
    tags: ["creative", "design", "automation"],
  },
  {
    id: "oneway",
    name: "OneWay",
    route: "/home/apps/OneWay/",
    domain: "oneway.blackroad.io",
    category: "gateway",
    oneLine: "One-way import and memory ingestion.",
    longDescription:
      "OneWay is the controlled ingestion layer: external APIs, exports, memories, and data streams enter BlackRoad through a one-way route so the system can remember without exposing itself backward.",
    primaryUser: "Operators importing data and wiring integrations.",
    replaces: ["Bidirectional risky connectors", "Untracked imports"],
    connectedProducts: ["roados", "roadchain", "roadwork", "roadtrip"],
    agentLayer: "Ingestion agents validate inputs, classify, and record provenance.",
    surfaceKind: "gateway",
    status: "partial",
    tags: ["ingest", "import", "memory"],
  },
  {
    id: "roadband",
    name: "RoadBand",
    route: "/home/apps/RoadBand/",
    domain: "roadband.blackroad.io",
    category: "creator",
    oneLine: "Music and audio creation with AI producer workflows.",
    longDescription:
      "RoadBand is music and audio creation: GarageBand plus AI producer workflows for beats, tracks, vocals, moods, lyrics, and songs.",
    primaryUser: "Musicians and creators.",
    replaces: ["Plugin sprawl", "Manual composition loops"],
    connectedProducts: ["blackboard", "backroad", "roados"],
    agentLayer: "Audio agents assist composition, arrangement, and mastering.",
    surfaceKind: "creator",
    status: "needs-review",
    tags: ["music", "audio", "creator"],
  },
  {
    id: "highway",
    name: "HighWay",
    route: "/home/apps/HighWay/",
    domain: "highway.blackroad.io",
    category: "subscription",
    oneLine: "Subscription and backbone layer connecting all roads.",
    longDescription:
      "HighWay is the umbrella subscription and backbone layer: users subscribe to the whole highway or individual roads/products — with clear entitlements and usage credits.",
    primaryUser: "Users managing access and billing across products.",
    replaces: ["Confusing bundles", "Disconnected billing surfaces"],
    connectedProducts: ["roadcoin", "carkeys", "roadside", "roados"],
    agentLayer: "Billing agents help users understand plans, credits, and entitlements.",
    surfaceKind: "subscription",
    status: "needs-review",
    tags: ["subscription", "billing", "access"],
  },
];

