import type { Site } from "./types";

export const SITES: Site[] = [
  {
    id: "blackroad-io",
    domain: "blackroad.io",
    url: "https://blackroad.io",
    title: "BlackRoad Home",
    type: "root",
    purpose: "Public front door and launcher into the ecosystem.",
    primaryCTA: "Open RoadOS",
    audience: "Public / new users",
    connectedProduct: "roados",
    connectedAgents: [],
    status: "partial",
    priority: 1,
    routes: [
      { path: "/home/", label: "Home" },
      { path: "/agents/", label: "Agents" },
      { path: "/atlas/", label: "Atlas" },
      { path: "/archive/", label: "Archive" },
    ],
    notes: "Root portal. Always routes back to RoadOS.",
  },
  {
    id: "os-blackroad-io",
    domain: "os.blackroad.io",
    url: "https://os.blackroad.io",
    title: "RoadOS",
    type: "runtime",
    purpose: "Portable browser computer.",
    primaryCTA: "Enter OS",
    audience: "Logged-in users",
    connectedProduct: "roados",
    connectedAgents: [],
    status: "partial",
    priority: 1,
    routes: [{ path: "/", label: "OS" }],
    notes: "The portable computer layer, not a marketing site.",
  },
  {
    id: "blackroad-company",
    domain: "blackroad.company",
    url: "https://blackroad.company",
    title: "BlackRoad OS, Inc.",
    type: "root",
    purpose: "Corporate identity and trust surface.",
    primaryCTA: "Open BlackRoad",
    audience: "Investors / customers / partners",
    connectedProduct: null,
    connectedAgents: [],
    status: "partial",
    priority: 2,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Keep compliance language crisp and accurate.",
  },
  {
    id: "blackroad-me",
    domain: "blackroad.me",
    url: "https://blackroad.me",
    title: "BlackRoad Me",
    type: "root",
    purpose: "Identity / agent / profile surface.",
    primaryCTA: "Open Agents",
    audience: "Users managing identity and agents",
    connectedProduct: "carkeys",
    connectedAgents: ["roadie", "lucidia"],
    status: "partial",
    priority: 2,
    routes: [
      { path: "/home/", label: "Home" },
      { path: "/agents/", label: "Agents" },
    ],
    notes: "Agent subdomains live here (`*.blackroad.me`).",
  },
  {
    id: "blackroad-network",
    domain: "blackroad.network",
    url: "https://blackroad.network",
    title: "BlackRoad Network",
    type: "infrastructure",
    purpose: "Network / mesh / node surface.",
    primaryCTA: "Open Systems",
    audience: "Operators / infra",
    connectedProduct: null,
    connectedAgents: ["octavia", "gematria"],
    status: "partial",
    priority: 3,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "RoadNode is opt-in only; do not imply hidden capture.",
  },
  {
    id: "blackroad-systems",
    domain: "blackroad.systems",
    url: "https://blackroad.systems",
    title: "BlackRoad Systems",
    type: "infrastructure",
    purpose: "Fleet and systems surface.",
    primaryCTA: "Open Network",
    audience: "Operators / fleet",
    connectedProduct: null,
    connectedAgents: ["octavia", "anastasia"],
    status: "partial",
    priority: 3,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "System status should be measurable and honest.",
  },
  {
    id: "blackroadai",
    domain: "blackroadai.com",
    url: "https://blackroadai.com",
    title: "BlackRoad AI",
    type: "root",
    purpose: "AI-facing brand and entry to agent surfaces.",
    primaryCTA: "Open OS",
    audience: "Users curious about agents and AI surfaces",
    connectedProduct: "roadtrip",
    connectedAgents: ["lucidia", "roadie"],
    status: "partial",
    priority: 2,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Keep claims grounded: real services or honest blockers.",
  },
  {
    id: "blackroad-inc-us",
    domain: "blackroadinc.us",
    url: "https://blackroadinc.us",
    title: "BlackRoad Inc.",
    type: "root",
    purpose: "Corporate and brand surface (US).",
    primaryCTA: "Open BlackRoad",
    audience: "Public / partners",
    connectedProduct: null,
    connectedAgents: [],
    status: "partial",
    priority: 3,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Keep trust language crisp; connect back to RoadOS.",
  },
  {
    id: "blackroad-qi",
    domain: "blackroadqi.com",
    url: "https://blackroadqi.com",
    title: "BlackRoad QI",
    type: "root",
    purpose: "Research and reasoning surface (QI).",
    primaryCTA: "Open OS",
    audience: "Researchers / builders",
    connectedProduct: null,
    connectedAgents: ["gematria", "sophia"],
    status: "partial",
    priority: 3,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Ground claims; link to RoadBook/RoadView as evidence surfaces.",
  },
  {
    id: "blackroad-quantum",
    domain: "blackroadquantum.com",
    url: "https://blackroadquantum.com",
    title: "BlackRoad Quantum",
    type: "root",
    purpose: "Quantum / advanced research brand surface.",
    primaryCTA: "Open OS",
    audience: "Researchers / partners",
    connectedProduct: null,
    connectedAgents: ["gematria"],
    status: "partial",
    priority: 3,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Avoid hype; connect to verifiable work in RoadBook/RoadChain.",
  },
  {
    id: "blackroad-quantum-docs",
    domain: "blackroadquantum.info",
    url: "https://blackroadquantum.info",
    title: "BlackRoad Quantum Docs",
    type: "root",
    purpose: "Documentation and reference surface for Quantum initiatives.",
    primaryCTA: "Open Docs",
    audience: "Researchers / builders",
    connectedProduct: "roadbook",
    connectedAgents: ["atticus"],
    status: "partial",
    priority: 4,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Prefer docs over marketing; keep it black-and-white.",
  },
  {
    id: "blackroad-quantum-network",
    domain: "blackroadquantum.net",
    url: "https://blackroadquantum.net",
    title: "BlackRoad Quantum Network",
    type: "infrastructure",
    purpose: "Network surface for Quantum initiatives.",
    primaryCTA: "Open Network",
    audience: "Operators / infra",
    connectedProduct: null,
    connectedAgents: ["octavia", "anastasia"],
    status: "partial",
    priority: 4,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Keep opt-in RoadNode language explicit.",
  },
  {
    id: "blackroad-quantum-shop",
    domain: "blackroadquantum.shop",
    url: "https://blackroadquantum.shop",
    title: "BlackRoad Quantum Shop",
    type: "root",
    purpose: "Commerce placeholder surface (until real shop is wired).",
    primaryCTA: "Open BlackRoad",
    audience: "Public",
    connectedProduct: null,
    connectedAgents: [],
    status: "needs-review",
    priority: 5,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "If commerce is not wired, fail honestly and link back to RoadOS.",
  },
  {
    id: "blackroad-quantum-store",
    domain: "blackroadquantum.store",
    url: "https://blackroadquantum.store",
    title: "BlackRoad Quantum Store",
    type: "root",
    purpose: "Commerce placeholder surface (until real store is wired).",
    primaryCTA: "Open BlackRoad",
    audience: "Public",
    connectedProduct: null,
    connectedAgents: [],
    status: "needs-review",
    priority: 5,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "If commerce is not wired, fail honestly and link back to RoadOS.",
  },
  {
    id: "blackboxprogramming",
    domain: "blackboxprogramming.io",
    url: "https://blackboxprogramming.io",
    title: "BlackBox Programming",
    type: "developer",
    purpose: "Developer identity and credibility surface.",
    primaryCTA: "Open RoadCode",
    audience: "Developers",
    connectedProduct: "roadcode",
    connectedAgents: ["cecilia", "sebastian"],
    status: "partial",
    priority: 3,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Developer-oriented routes and docs should live here.",
  },
  {
    id: "aliceqi",
    domain: "aliceqi.com",
    url: "https://aliceqi.com",
    title: "Alice",
    type: "agent",
    purpose: "Alice surface (identity + gateway agent).",
    primaryCTA: "Open Agents",
    audience: "Public / operator",
    connectedProduct: null,
    connectedAgents: ["alice"],
    status: "partial",
    priority: 5,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "If no agent actions are wired, be explicit about what exists.",
  },
  {
    id: "lucidia-earth",
    domain: "lucidia.earth",
    url: "https://lucidia.earth",
    title: "Lucidia",
    type: "root",
    purpose: "Stewardship / environment / public-good surface.",
    primaryCTA: "Open OS",
    audience: "Public",
    connectedProduct: null,
    connectedAgents: ["gaia", "lucidia"],
    status: "partial",
    priority: 4,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Keep claims grounded and measurable.",
  },
  {
    id: "lucidia-studio",
    domain: "lucidia.studio",
    url: "https://lucidia.studio",
    title: "Lucidia Studio",
    type: "root",
    purpose: "Creative studio surface for Lucidia/BlackBoard/RoadBand.",
    primaryCTA: "Open BlackBoard",
    audience: "Creators",
    connectedProduct: "blackboard",
    connectedAgents: ["lucidia", "lyra"],
    status: "partial",
    priority: 4,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Connect to real creative surfaces; avoid decorative dead ends.",
  },
  {
    id: "lucidia-qi",
    domain: "lucidiaqi.com",
    url: "https://lucidiaqi.com",
    title: "Lucidia QI",
    type: "root",
    purpose: "Research and intelligence surface for Lucidia QI.",
    primaryCTA: "Open RoadView",
    audience: "Researchers / builders",
    connectedProduct: "roadview",
    connectedAgents: ["gematria", "sophia"],
    status: "partial",
    priority: 4,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Prefer evidence and citations; link to RoadBook/RoadChain.",
  },
  {
    id: "roadchain-io",
    domain: "roadchain.io",
    url: "https://roadchain.io",
    title: "RoadChain",
    type: "product",
    purpose: "Public RoadChain surface.",
    primaryCTA: "Open RoadChain App",
    audience: "Public / compliance / proof",
    connectedProduct: "roadchain",
    connectedAgents: ["gematria"],
    status: "partial",
    priority: 3,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Frame as provenance + audit, not hype.",
  },
  {
    id: "roadcoin-io",
    domain: "roadcoin.io",
    url: "https://roadcoin.io",
    title: "RoadCoin",
    type: "product",
    purpose: "Public RoadCoin surface (utility credits framing).",
    primaryCTA: "Open RoadCoin App",
    audience: "Contributors",
    connectedProduct: "roadcoin",
    connectedAgents: ["valeria"],
    status: "partial",
    priority: 3,
    routes: [{ path: "/home/", label: "Home" }],
    notes: "Utility credits, not investment money.",
  },
];
